def generate_davinci_config(dataset_path, particle='Jpsi', stripping_line='REPLACE_ME', stream='Dimuon', year='2012'):
    """
    Generates a DaVinci configuration script (macro) for LHCb data processing.
    """
    template = f"""from Configurables import DaVinci, DecayTreeTuple
from DecayTreeTuple.Configuration import *
from GaudiConf import IOHelper

# This configuration was automatically generated by the CERN Open Data Explorer

stream = '{stream}'
line = '{stripping_line}' 

dtt = DecayTreeTuple('Tuple{particle}ToMuMu')
dtt.Inputs = ['/Event/{{0}}/Phys/{{1}}/Particles'.format(stream, line)]
dtt.Decay = 'J/psi(1S) -> mu+ mu-'

DaVinci().UserAlgorithms += [dtt]
DaVinci().InputType = 'DST'
DaVinci().TupleFile = '{particle}_ntuple.root'
DaVinci().EvtMax = -1
DaVinci().PrintFreq = 10000
DaVinci().DataType = '{year}'
DaVinci().Simulation = False
DaVinci().Lumi = True

IOHelper().inputFiles(['{dataset_path}'])
    """
    return template

if __name__ == "__main__":
    # legacy behavior
    print(generate_davinci_config('data/00041834_00013937_1.dimuon.dst'))
